/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface BookResponse {
  archived?: boolean;
  authorName?: string;
  bookCover?: Array<string>;
  id?: number;
  isbn?: string;
  owner?: User;
  rate?: number;
  shareable?: boolean;
  synopsis?: string;
  title?: string;
}
