/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface BorrowedBookResponse {
  authorName?: string;
  id?: number;
  isbn?: string;
  owner?: User;
  rate?: number;
  returnApproved?: boolean;
  returned?: boolean;
  title?: string;
}
