spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: USERNAME
    password: PASSWORD
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgresSLDialect
  mail:
    host: localhost
    port: 1025
    username: ephrem
    password: ephrem
    properties:
      mail:
        smtp:
          trues: "*"
        auth: true
        starttls:
          enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
      
        
      
      
    