/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getAllFeedbacks } from '../fn/feedbacks/get-all-feedbacks';
import { GetAllFeedbacks$Params } from '../fn/feedbacks/get-all-feedbacks';
import { giveFeedBack } from '../fn/feedbacks/give-feed-back';
import { GiveFeedBack$Params } from '../fn/feedbacks/give-feed-back';
import { PageResponseFeedbackResponse } from '../models/page-response-feedback-response';

@Injectable({ providedIn: 'root' })
export class FeedbacksService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `giveFeedBack()` */
  static readonly GiveFeedBackPath = '/feedbacks/book/';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `giveFeedBack()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  giveFeedBack$Response(params: GiveFeedBack$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return giveFeedBack(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `giveFeedBack$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  giveFeedBack(params: GiveFeedBack$Params, context?: HttpContext): Observable<number> {
    return this.giveFeedBack$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `getAllFeedbacks()` */
  static readonly GetAllFeedbacksPath = '/feedbacks/book/{bookId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllFeedbacks()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllFeedbacks$Response(params: GetAllFeedbacks$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseFeedbackResponse>> {
    return getAllFeedbacks(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllFeedbacks$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllFeedbacks(params: GetAllFeedbacks$Params, context?: HttpContext): Observable<PageResponseFeedbackResponse> {
    return this.getAllFeedbacks$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseFeedbackResponse>): PageResponseFeedbackResponse => r.body)
    );
  }

}
